### ISSUE TITLE
SPA & Static

### ISSUE THREAD

**Issue by JesusCrow** [nuxt-community/proxy-module#1]
This module seems to be incompatible with static and SPA modes (because only server calls are rewritten). I would like to get a confirmation for this statement, then we could do something like:

1. Add disclaimer in README.md and during `nuxt generate`
2. Add disclaimer in modules that use this module (like axios module?)
3. Consider a way for this plugin to work for other modes (rewriting URL's during generating?)

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/proxy-module/issues/c1">#c1</a>)</em></sub></div>

**Comment by manniL** [comment]
@JesusCrow You are right!

I'd appreciate a PR for the documentation/README files of at least this module.

**Comment by manniL** [comment]
#10

**Comment by manniL** [comment]
I don't think there is a "suitable" way to make it working for SPA/generated mode.

URL rewrites are something different than using a proxy. Leaving people using that package in the belief that they'll achieve "the same" is wrong IMO.

**Comment by maximilliangeorge** [comment]
Excuse my superficial server knowledge but can't a static server also forward a request to another server? I understand that a static build directory does not *by itself* have this capacity, but it would be awesome if `npm start` (which runs a local server for testing) could proxy requests to the API. This is what we're doing on our production server.
