### ISSUE TITLE
Fix warning about vite.config.js

### ISSUE THREAD

**Issue by edwh** [nuxt-community/proxy-module#120]
`WARN  Using vite.config.js is not supported together with Nuxt. Use options.vite instead. You can read more in https://nuxt.com/docs/api/configuration/nuxt-config#vite.`

This issue to to move that config into `nuxt.config.ts` and also test that whatever we have moved still works.

**Comment by titusdecali** [comment]
Wnat about cases where we need two vite.config files? (I have a separate widget builder which requires its own config)

**Comment by edwh** [comment]
Sorry, I raised this on the wrong repo.
