### ISSUE TITLE
POST requests with payload are not send to endpoint

### ISSUE THREAD

**Issue by zajca** [nuxt-community/proxy-module#13]
I run into this problem.

When I have proxy set like this:

```
  proxy: {
    '/api/':{ target: process.env.API_URL, pathRewrite: {'^/api/': ''}, logLevel: 'debug' }
  },
  axios: {
    proxy: true
  },
```

when I send post to url is processed by backed just fine
`this.$axios.$post('/api/non-existing-url') -> 404`

But when i set payload like this:
```
      this.$axios.$post('/jh-api/non-existing-url', {
        form': {}
      })
->
Request failed with status code 504
✖ error nuxt › proxy › [HPM] Error occurred while trying to proxy request non-existing-url from localhost:3000 to http://127.0.0.1:8082 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

proxy-module: 1.3.1
nuxtjs/axios:  5.3.4
nuxt: 2.2.0

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/proxy-module/issues/c11">#c11</a>)</em></sub></div>

**Comment by alexanderniebuhr** [comment]
I fixed, with workaround of official github

https://github.com/chimurai/http-proxy-middleware/issues/320

**Comment by Venikeee1** [comment]
I fixed this issue by 'coexist-parser-proxy'. You should put it above bodyParser in `nuxt.config.js`
`
const bodyParser  = require('body-parser');

module.exports = {
  serverMiddleware: [
    'coexist-parser-proxy', // Needs to be before bodyParser
    bodyParser.json()
  ],
  proxy: {
    '/api': 'some url',
  }
}`

**Comment by TheMangoTrain** [comment]
This works for me, thx.

For future: is there a pathway to not have this workaround dependency?

**Comment by root5427** [comment]
> const bodyParser  = require('body-parser');
> 
> module.exports = {
>   serverMiddleware: [
>     'coexist-parser-proxy', // Needs to be before bodyParser
>     bodyParser.json()
>   ],
>   proxy: {
>     '/api': 'some url',
>   }
> }

Any updates on this? Are you guys still using this workaround?
