### ISSUE TITLE
onProxyReq?

### ISSUE THREAD

**Issue by appinteractive** [nuxt-community/proxy-module#18]
How can I use the onProxyReq or what is the best way to alter the header based on a value on the `app`object?

**Comment by karahan** [comment]
@appinteractive did you find a solution on this? It's an old topic i know :S

**Comment by NoahCardoza** [comment]
I'm wondering the same thing, adding `onProxyReq` doesn't seem to have any effect...

**Comment by appinteractive** [comment]
@NoahCardoza as far as I can remember, I just stoped using it as the support did not exist in any shape or form. 😔
