### ISSUE TITLE
Support HTTP/2 server

### ISSUE THREAD

**Issue by japboy** [nuxt-community/proxy-module#2]
I need HTTP/2 server support

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/proxy-module/issues/c2">#c2</a>)</em></sub></div>

**Comment by ricardogobbosouza** [comment]
@japboy 
I need some idea how to deploy this

**Comment by ricardogobbosouza** [comment]
@japboy see
https://github.com/chimurai/http-proxy-middleware/issues/79#issuecomment-240924679

**Comment by ricardogobbosouza** [comment]
@pi0 can close?

**Comment by pi0** [comment]
Please do **NOT** use a custom express server for H2 support. This solution is not recommend.

Nuxt has built-in http2 push and ssl support (which is a requirement for h2 by browsers)

But an upfront reverse proxy (like nginx or cloud flare) is recommend to simplify process.
