### ISSUE TITLE
How to setToken with axios-module for multiple API's

### ISSUE THREAD

**Issue by samuells** [nuxt-community/proxy-module#4]
Hi,

I have 2 api, from which I need to get data. Both of them are using Bearer authentication token - but this token is different for each api. How can I set token to the axios, if I am using proxy to switch baseURL, but the token is set on the axios instance? 

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/proxy-module/issues/c3">#c3</a>)</em></sub></div>

**Comment by hqqxxf** [comment]
I have the same question

**Comment by yoann54** [comment]
Hello,

Did u find a solution to this problem ?  i have exactly the same and i don't find any docs on how to manage multiple api at the same time .

**Comment by diegotejadav** [comment]
@samuells @hqqxxf @yoann54, same question here, did some of you find any solution or example?

**Comment by samuells** [comment]
No luck .. I didn't dig more on this.

**Comment by llavre** [comment]
@samuells why did you don't create two axios instances?

In my case one for public and one for private apis.

**Comment by samuells** [comment]
It was a long time ago ... but I was trying achieve using nuxt settings file .. not sure anymore. Sorry

**Comment by LTroya** [comment]
@llavre how can you create two instances of `$axios`? `axios` has a `create` method for doing that

**Comment by llavre** [comment]
You should create two needed axios instances like
`let privateAPI = axios.create({ baseURL: PRIVATE_API_URL })`

and then inject it in to context trough nuxt plugin.

**Comment by cranx** [comment]
According to docs:

> If you need the function in the `context`, Vue instances and maybe even in the Vuex store, you can use the `inject` function, which is the second parameter of the plugins exported function.

So just `inject` should be enough
