### ISSUE TITLE
 Error in created hook (Promise/async): "Error: connect ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by warheartvik** [nuxt-community/proxy-module#47]
Hello,

After installing que configuring @nuxtjs/proxy as is shown in [https://nuxtjs.org/faq/http-proxy/](url), I'm getting this warn con server side console:

Error in created hook (Promise/async): "Error: connect ECONNREFUSED 127.0.0.1:80

I'm using axios.

Any advise? Something I could look up?

Best regards

**Comment by snsxn** [comment]
I'm with the same error. 

Did you solved?

**Comment by sp1r1don** [comment]
proxy server had expired SSL
