### ISSUE TITLE
How to consume data from two diferent Api´s?

### ISSUE THREAD

**Issue by amrigo** [nuxt-community/proxy-module#48]
I am using NuxtJs, and need to consume Json data from two diferent Api´s.

The first Api is working, and the second Api is not working.

I follow the instructions from this link :

At nuxtjs.config i have these lines below and both url´s are retrieving data as expected:

```
proxy: {
    '/api': {
      target: 'http://localhost/api/stores',
      pathRewrite: {
        '^/api' : '/'
        }
      },
      '/apiCategories': {
        target: 'http://localhost/api/get_categories',
        pathRewrite: {
          '^/apiCategories' : '/apiCategories'
          }
        }
  }
```
At pages/index.vue at the created hook i set :

```
 created() {    
        Axios.get('/api')
          .then(response => {
            this.stores = response.data
          })
          .catch(error => {
            console.log('There was an error:', error.response)
          }),

          Axios.get('/apiCategories')
          .then(response => {
            this.options = response.data,
          })
          .catch(error => {
            console.log(' There was an error at apiCategories: ', error.response) 
          })
    },
```
The `/api` is working right, while the `/apicategories` gives me the error message :

`commons.app.js:199 GET http://localhost:3000/apiCategories 404 (Not Found) `

Runnnig the url http://localhost:3000/apiCategories at the browser gives me the expected Json data.

Wich is the right way to consume from two diferent Api´s using NuxtJs or proxy module ?

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/proxy-module/issues/c24">#c24</a>)</em></sub></div>

**Comment by bagaskarala** [comment]
i assume tha path rewrite is not right, change to this
```
        pathRewrite: {
          '^/apiCategories' : '/'
          }
        }
```
