### ISSUE TITLE
Use proxy module with company proxy

### ISSUE THREAD

**Issue by mpgalaxy** [nuxt-community/proxy-module#66]
### What problem does this feature solve?

Currently the proxy module can't make use of a company proxy server, resulting in timeout with external identity provider(e.g. keycloak), which is being proxied through /auth. Although the docker container is configured properly for using the company proxy, nuxt.js and especially the nuxt proxy module don't utilize these settings.

### What does the proposed changes look like?

Add a boolean flag as well as configuration option for nuxt.config to utilize the company proxy server, e.g.:
```javascript
proxy: {
    '/auth': {
      target:
        (process.env.KEYCLOAK_SCHEME || 'http') +
        '://' +
        (process.env.KEYCLOAK_HOST || 'localhost') +
        ':' +
        (process.env.KEYCLOAK_PORT || '8080'),
      useCompanyProxy: true,
      companyProxy: process.env.COMPANY_HTTP_PROXY // example: http://companyproxy:8888
    },
...
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/proxy-module/issues/c36">#c36</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi :)

You can simply compute it inside `nuxt.config.js`:

```js
function getAuthproxy(useCompanyProxy) {
  if (useCompanyProxy) {
    const { COMPANY_HTTP_PROXY } = process.env
    if (!COMPANY_HTTP_PROXY) {
      throw new Error('COMPANY_HTTP_PROXY environment variable should be set!')
    }
    return COMPANY_HTTP_PROXY 
  }
  const { KEYCLOAK_SCHEME, KEYCLOAK_HOST, KEYCLOAK_PORT } = process.env
  return (KEYCLOAK_SCHEME || 'http') + '://' + (KEYCLOAK_HOST || 'localhost') + ':' + (KEYCLOAK_PORT || '8080')
}

export default {
  proxy: {
    '/auth': { 
      target: getAuthproxy(true /* useCompanyProxy */)
    }
  }
}
```
