### ISSUE TITLE
Cors issues

### ISSUE THREAD

**Issue by paulogr** [nuxt-community/proxy-module#67]
Hi, I'm trying to proxy some requests during development to avoid cors issues but getting this error:

`Access to XMLHttpRequest at 'https://gateway.boaconsulta.com/api/v1/cep/01322-050' (redirected from 'http://localhost:3000/cep/01322-050') from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

My nuxt.config.js is configured as follow:

```
axios: {
  proxy: true
},
proxy: {
  '/cep/': { target: 'http://gateway.boaconsulta.com/api/v1/' }
},
```

I'm calling the service this way on the client side:

```
async resolveCep () {
  await this.$axios.get(`/cep/${this.data.zip}`)
}
```

I see on Chrome devtools the origin header to the target url is still `http://localhost:3000`, but the `changeOrigin` option isn't about rewrite the origin header to the target url?

What I'm doing wrong?

Appreciate any help.

**Comment by paulogr** [comment]
forgot, my bad

**Comment by CHEWX** [comment]
@paulogr You're bad for what? How did you resolve?

**Comment by piotrku** [comment]
yeah @paulogr, the same problem here - what did you do? :)

**Comment by usefss** [comment]
@paulogr, oh come on this is exactly what I am dealing with past 3 hours...

**Comment by usefss** [comment]
oh ok! I accept it is very shameful but the problem for me solved with changing 
```
fetch(document.location.origin + '/api/auth/login/', {
```
to 
```
fetch(document.location.origin + '/api/auth/login', {
```
* notice deleting / from end of url :)
