### ISSUE TITLE
Update version in npm

### ISSUE THREAD

**Issue by TrueCarry** [nuxt-community/proxy-module#68]
### What problem does this feature solve?

Currently published proxy module relies on http-proxy-middleware@0.19.2, which uses some outdated dependencies. In repository package.json already uses ^0.20.0, but after I removed @nuxtjs/axios and installed it back, I still got http-proxy-middleware@0.19.2.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/proxy-module/issues/c42">#c42</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi. Just published 2.0.0 using http-proxy-middleware@1.x (just to ensure there is no regressions). Axios and HTTP modules will update dependency accordingly
