### ISSUE TITLE
Question: Proxy based on full url

### ISSUE THREAD

**Issue by paulogr** [nuxt-community/proxy-module#69]
Hello, I have a question here.

When I have proxy enabled I want to proxy full urls, but it doesn't work.

```
proxy: {
  'https://api.example.io': 'https://api.example.io'
}
```

What i'm trying to archive is that all request to `api.example.io` goes thru proxy.

Thank you

**Comment by pi0** [comment]
Hi @paulogr It is not purpose of proxy-module. You may use an axios interceptor ([onRequest](https://axios.nuxtjs.org/helpers.html#interceptors) to rewrite `api.example.io` to `/api` then a proxy rule like: 

```js
proxy: {
  '/api': 'https://api.example.io'
}
```
