### ISSUE TITLE
HPM error occured

### ISSUE THREAD

**Issue by stephenjason89** [nuxt-community/proxy-module#98]
[HPM] Error occurred while trying to proxy request /api/ntp from localhost:3000 to http://localhost:8000 (HPE_INVALID_CONSTANT) (https://nodejs.org/api/errors.html#errors_common_system_errors)

This is while trying to just access a page which returns an unix timestamp.
Weird thing is it is like a switch.
It works then after a refresh it won't work, then refresh again, it won't work again, refresh again then it work, refresh again then it don't work again.

![image](https://user-images.githubusercontent.com/3810177/114319224-29b87280-9b43-11eb-8d0e-539634629934.png)
![image](https://user-images.githubusercontent.com/3810177/114319230-3341da80-9b43-11eb-9f03-711187115cb7.png)

I mean it is really consistent, every other request throws an error
this is my laravel route

Route::get('ntp', function () { echo (string) round($_SERVER['REQUEST_TIME_FLOAT'] * 1000); });

If i visit it directly using localhost:8000 then there are no problems

**Comment by abas1991** [comment]
+1
